import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from "./components/Footer";
import Link from "next/link";
import {useEffect, useState} from "react";

export default function Home() {
    const [isDesktop, setIsDesktop] = useState(false);
    const newFeature = true;

    useEffect(() => {
        setIsDesktop(window.innerWidth > 768); // set to true if screen width is greater than 768px (desktop)
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Iftaar 23</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <br/>
            {isDesktop &&
                <Link href="https://github.com/hamzafer/iftaar-web-app" target="_blank" rel="noopener noreferrer">
                    <button style={{
                        backgroundColor: '#0662da',
                        border: 'none',
                        color: 'white',
                        padding: '10px 20px',
                        textAlign: 'center',
                        textDecoration: 'none',
                        display: 'inline-block',
                        fontSize: '16px',
                        margin: '10px',
                        borderRadius: '5px',
                        cursor: 'pointer'
                    }}>
                        Contribute
                    </button>
                </Link>}
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to Iftaar 23!
                </h1>
                <br/>
                <div className={styles.grid}>
                    <Link href="/timeline" className={styles.card}>
                        <h2>View Timeline &rarr;</h2>
                        <p>Checkout the whole Ramadan Iftaar timeline!</p>
                    </Link>

                    <Link href="/next-iftaar" className={styles.card}>
                        <h2>View Next Iftaar &rarr;</h2>
                        <p>See who is next in the list to host!</p>
                    </Link>

                    <Link href="/gallery" className={styles.card}>
                        <h2>Gallery &rarr;</h2>
                        <p>See the dump!</p>
                        <br/>
                        {newFeature &&
                            <span className={styles["new"]}>
                                NEW
                            </span>}
                    </Link>
                </div>
            </main>
            <Footer/>
        </div>
    )
}
