import styles from "../styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";
import React, {useEffect, useState} from "react";
import Footer from "./components/Footer";
import Image from "next/image";
import Loader from "./components/Loader";

export default function NextIftaar() {
    const host = "Chuchu";
    const image = `/${host}.jpg`;
    const [iftaarData, setIftaarData] = useState([]);
    const [isLoading, setIsLoading] = useState(true);

    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    useEffect(() => {
        async function fetchIftaarData() {
            try {
                const response = await fetch('/api/iftaarData');
                const data = await response.json();
                setIftaarData(data);
                setIsLoading(false);
            } catch (error) {
                console.error('Error fetching iftaar data:', error);
            }
        }

        fetchIftaarData();
    }, []);

    const hostData = iftaarData.find((data) => data.name === host);
    const hostDate = hostData?.date ?? "TBD";
    const date = new Date(hostDate);
    const dayOfWeek = date.getDay();
    const daysOfWeek = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    const day = daysOfWeek[dayOfWeek];

    return (
        <div className={styles.container}>
            <Head>
                <title>Iftaar 23 | Next</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Link href="/">
                    <span className={styles.logo}>
                        <p>Home</p>
                    </span>
            </Link>
            {isLoading ? (
                    <Loader/>
                ) :
                <div
                    style={{
                        display: "flex",
                        justifyContent: "center",
                        flexDirection: "column",
                        alignItems: "center",
                    }}
                >
                    <h1>Next Iftaar : {hostDate} | {day}</h1>
                    <Image
                        src={image}
                        alt="Next Iftaar"
                        width={200}
                        height={200}
                        style={{borderRadius: "50%", width: "200px", height: "200px"}}
                    />
                    <p>{host}</p>

                    <Link href="/timeline">
                        <p>- click here for the timeline -</p>
                    </Link>
                </div>}
            <Footer/>
        </div>
    );
}
