import styles from "../styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import Footer from "./Components/Footer";

export default function NextIftaar() {
    const host = 'Hasan bin Tariq';
    const image = '/ibnet.jpg';

    return (
        <div className={styles.container}>
            <Head>
                <title>Iftaar 23 | Next</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Link href="/">
                    <span className={styles.logo}>
                        <p>Home</p>
                    </span>
            </Link>
            <div style={{display: 'flex', justifyContent: 'center', flexDirection: 'column', alignItems: 'center'}}>
                <h1>Next Iftaar</h1>
                <img src={image} alt="Next Iftaar" style={{borderRadius: '50%', width: '200px', height: '200px'}}/>
                <p>{host}</p>

                <a href="/timeline">
                    <p>- checkout the whole timeline -</p>
                </a>
            </div>
            <Footer/>
        </div>
    );
}

