import React from 'react';
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Footer from "./Components/Footer";

export default function Timeline() {
    const iftaarData = [
        {id: 1, name: 'Saad', date: 'TBD', location: 'Chiniot'},
        {id: 2, name: 'Ibnet', date: 'April 1, 2023', location: `Ibnet's home`},
        {id: 3, name: 'Sohaib', date: 'March 28, 2023', location: `Sohaib's home`},
        {id: 4, name: 'Chuchu', date: 'TBD', location: `Chuchu's home`},
        {id: 5, name: 'Ahnuf + Munir', date: 'TBD', location: `TBD`},
        {id: 6, name: 'Afnan', date: 'TBD', location: `Afnan's home`},
        {id: 7, name: 'Kagge', date: 'TBD', location: `Kagge's home`},
        {id: 8, name: 'Yasir', date: 'TBD', location: `Yasir's home`},
        {id: 9, name: 'TZ + Hamza Bhai', date: 'TBD', location: `Four seasons`},
        {id: 10, name: 'Jamil', date: 'TBD', location: `Jamil's home`},
    ];

    return (
        <div className={styles.container}>
            <Head>
                <title>Iftaar 23 | Timeline</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Link href="/">
                    <span className={styles.logo}>
                        <p>Home</p>
                    </span>
            </Link>
            <div style={{textAlign: 'center'}}>
                <h1>Timeline</h1>
                <div style={{display: 'inline-block', border: '1px solid white', padding: '20px'}}>
                    <table style={{borderCollapse: 'collapse', margin: 'auto'}}>
                        <thead>
                        <tr>
                            <th style={{border: '1px solid white', padding: '10px'}}>Sr.</th>
                            <th style={{border: '1px solid white', padding: '10px'}}>Name</th>
                            <th style={{border: '1px solid white', padding: '10px'}}>Date</th>
                            <th style={{border: '1px solid white', padding: '10px'}}>Location</th>
                        </tr>
                        </thead>
                        <tbody>
                        {iftaarData.map(({id, name, date, location}) => (
                            <tr key={name}>
                                <td style={{border: '1px solid white', padding: '10px'}}>{id}</td>
                                <td style={{border: '1px solid white', padding: '10px'}}>{name}</td>
                                <td style={{border: '1px solid white', padding: '10px'}}>{date}</td>
                                <td style={{border: '1px solid white', padding: '10px'}}>{location}</td>
                            </tr>
                        ))}
                        </tbody>
                    </table>
                </div>
            </div>
            <br/>
            <Footer/>
        </div>
    );
}
