import React, {useEffect, useState} from 'react';
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Footer from "./components/Footer";
import stylesT from '../styles/Timeline.module.css'
import Loader from "./components/Loader";

export default function Timeline() {
    const [iftaarData, setIftaarData] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
    const [nextIftaarIndex, setNextIftaarIndex] = useState(-1);

    useEffect(() => {
        async function fetchIftaarData() {
            try {
                const response = await fetch('/api/iftaarData');
                const data = await response.json();
                setIftaarData(data);

                const now = new Date();
                const nextIftaarIndex = data.findIndex(
                    ({date}) => new Date(date) > now
                );
                setNextIftaarIndex(nextIftaarIndex);

                setIsLoading(false);
            } catch (error) {
                console.error('Error fetching iftaar data:', error);
            }
        }

        fetchIftaarData();
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Iftaar 23 | Timeline</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Link href="/">
                    <span className={styles.logo}>
                        <p>Home</p>
                    </span>
            </Link>
            {isLoading ? (
                    <Loader/>
                ) :
                <div style={{textAlign: 'center'}}>
                    <h1>Timeline</h1>
                    <div style={{display: 'inline-block', border: '1px solid white', padding: '20px'}}>
                        <table style={{borderCollapse: 'collapse', margin: 'auto'}}>
                            <thead>
                            <tr>
                                <th style={{border: '1px solid white', padding: '10px'}}>Sr.</th>
                                <th style={{border: '1px solid white', padding: '10px'}}>Name</th>
                                <th style={{border: '1px solid white', padding: '10px'}}>Date</th>
                                <th style={{border: '1px solid white', padding: '10px'}}>Location</th>
                            </tr>
                            </thead>
                            <tbody>
                            {iftaarData.map(({id, name, date, location, done}, index) => (
                                <tr
                                    key={name}
                                    className={
                                        done ? stylesT["row-done"] :
                                            nextIftaarIndex === index ? stylesT["row-next"] : null
                                    }
                                >
                                    <td style={{border: '1px solid white', padding: '10px'}}>{id}</td>
                                    <td style={{border: '1px solid white', padding: '10px'}}>{name}</td>
                                    <td style={{border: '1px solid white', padding: '10px'}}>{date}</td>
                                    <td style={{border: '1px solid white', padding: '10px'}}>{location}</td>
                                </tr>
                            ))}
                            </tbody>
                        </table>
                        <div
                            style={{
                                display: "flex",
                                justifyContent: "center",
                                marginTop: "1rem"
                            }}
                        >
                            <div style={{ display: "flex", alignItems: "center" }}>
                                <div
                                    style={{
                                        width: "1rem",
                                        height: "1rem",
                                        backgroundColor: "#d70354",
                                        marginRight: "0.5rem"
                                    }}
                                />
                                <span>Next iftaar</span>
                            </div>
                            <div style={{ display: "flex", alignItems: "center", marginLeft: "1rem" }}>
                                <div
                                    style={{
                                        width: "1rem",
                                        height: "1rem",
                                        backgroundColor: "#3a86ff",
                                        marginRight: "0.5rem"
                                    }}
                                />
                                <span>Done</span>
                            </div>
                        </div>
                    </div>
                </div>}
            <br/>
            <Footer/>
        </div>
    );
}
